#!/bin/bash
# *****************************************************************************
# gridder - Set active window position and size on a custom grid
#
# Syntax:
#
# gridder gridcols gridrows col row cols rows
#
# Parameters:
#
# gridcols    The number of columns in the grid.
# gridrows    The number of rows in the grid.
# col         The column at which to place the window. First column is zero.
# row         The row at which to place the window. First row is zero.
# cols        The width of the window in columns. Maximum is gridcols minus col.
# rows        The height of the window in rows. Maximum is gridrows minus row.
#
# Dependencies:
#
# xdotool
# xdpyinfo
#
# *****************************************************************************
if [ "$#" -ne 6 ]; then
    echo "Wrong number of arguments."
    echo "Syntax:"
    echo "  gridder gridcols gridrows col row cols rows"
    exit 1
fi

GRIDCOLS=$1
GRIDROWS=$2
COL=$3
ROW=$4
COLS=$5
ROWS=$6
#SCREENWIDTH=$(xdpyinfo | grep dimensions | sed -r 's/^[^0-9]*(([0-9]+)x([0-9]+)).*$/\2/')
#SCREENHEIGHT=$(xdpyinfo | grep dimensions | sed -r 's/^[^0-9]*(([0-9]+)x([0-9]+)).*$/\3/')
# Get usable desktop size 
SCREENWIDTH=$(xprop -root _NET_WORKAREA | sed -r 's/^[^0-9]*([0-9]+), ([0-9]+), ([0-9]+), ([0-9]+)/\3/')
SCREENHEIGHT=$(xprop -root _NET_WORKAREA | sed -r 's/^[^0-9]*([0-9]+), ([0-9]+), ([0-9]+), ([0-9]+)/\4/')
# Get dimensions of window decorations (titlebar + border)
BORDERS=$(xprop _NET_FRAME_EXTENTS -id $(xdotool getactivewindow))
BORDERLEFT=$(echo $BORDERS | sed -r 's/^[^0-9]*([0-9]+), ([0-9]+), ([0-9]+), ([0-9]+)/\1/')
BORDERRIGHT=$(echo $BORDERS | sed -r 's/^[^0-9]*([0-9]+), ([0-9]+), ([0-9]+), ([0-9]+)/\2/')
BORDERTOP=$(echo $BORDERS | sed -r 's/^[^0-9]*([0-9]+), ([0-9]+), ([0-9]+), ([0-9]+)/\3/')
BORDERBOTTOM=$(echo $BORDERS | sed -r 's/^[^0-9]*([0-9]+), ([0-9]+), ([0-9]+), ([0-9]+)/\4/')
COLWIDTH=$(expr $((SCREENWIDTH / GRIDCOLS)))
ROWHEIGHT=$(expr $((SCREENHEIGHT / GRIDROWS)))
WINDOWWIDTH=$(expr $((COLWIDTH * COLS)))
WINDOWHEIGHT=$(expr $((ROWHEIGHT * ROWS)))
XPOS=$(expr $((COL * COLWIDTH)))
YPOS=$(expr $((ROW * ROWHEIGHT)))
xdotool getactivewindow windowsize $((WINDOWWIDTH - (BORDERLEFT + BORDERRIGHT))) $((WINDOWHEIGHT - (BORDERTOP + BORDERBOTTOM)))
#logger "gridder: WINDOWHEIGHT: $WINDOWHEIGHT; BORDERTOP: $BORDERTOP; BORDERBOTTOM: $BORDERBOTTOM"

# Fix for Konsole window positioning. Konsole for some reason behaves differently from other windows, the vertical position is exactly one BORDERTOP lower. So with this hack the result is as expected, but the cause of this is unclear.
if [[ $(xdotool getactivewindow getwindowname) =~ "Konsole" ]]; then
  xdotool getactivewindow windowmove $XPOS $((YPOS + BORDERTOP))
else
  xdotool getactivewindow windowmove $XPOS $YPOS
fi
#logger "gridder: YPOS: $YPOS"
