#!/bin/bash
# *****************************************************************************
# gridder - Set active window position and size on a custom grid
#
# Syntax:
#
# gridder gridcols gridrows col row cols rows
#
# Parameters:
#
# gridcols    The number of columns in the grid.
# gridrows    The number of rows in the grid.
# col         The column at which to place the window. First column is zero.
# row         The row at which to place the window. First row is zero.
# cols        The width of the window in columns. Maximum is gridcols minus col.
# rows        The height of the window in rows. Maximum is gridrows minus row.
#
# Dependencies:
#
# xdotool
# xdpyinfo
#
# *****************************************************************************
if [ "$#" -ne 6 ]; then
    echo "Wrong number of arguments."
    echo "Syntax:"
    echo "  gridder gridcols gridrows col row cols rows"
    exit 1
fi

GRIDCOLS=$1
GRIDROWS=$2
COL=$3
ROW=$4
COLS=$5
ROWS=$6
SCREENWIDTH=$(xdpyinfo | grep dimensions | sed -r 's/^[^0-9]*(([0-9]+)x([0-9]+)).*$/\2/')
SCREENHEIGHT=$(xdpyinfo | grep dimensions | sed -r 's/^[^0-9]*(([0-9]+)x([0-9]+)).*$/\3/')
COLWIDTH=$(expr $((SCREENWIDTH / GRIDCOLS)))
ROWHEIGHT=$(expr $((SCREENHEIGHT / GRIDROWS)))
WINDOWWIDTH=$(expr $((COLWIDTH * COLS)))
WINDOWHEIGHT=$(expr $((ROWHEIGHT * ROWS)))
XPOS=$(expr $((COL * COLWIDTH)))
YPOS=$(expr $((ROW * ROWHEIGHT)))
xdotool getactivewindow windowsize $WINDOWWIDTH $WINDOWHEIGHT
xdotool getactivewindow windowmove $XPOS $YPOS
